kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: postgres-data
spec:
   storageClassName: px-postgres-sc
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
