kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-data
  labels:
    app: nginx
spec:
  storageClassName: portworx-proxy-volume-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
