kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-proxy-volume-volume
provisioner: kubernetes.io/portworx-volume
parameters:
  proxy_endpoint: "nfs://192.168.101.90"
  proxy_nfs_exportpath: "/var/nfs"
allowVolumeExpansion: true
