apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: freebsd-image
  namespace: pxbbq
spec:
  source:
    http:
      url: "https://px-deploy.s3.eu-west-1.amazonaws.com/image/freebsd-13.2-zfs-2023-04-21.qcow2"
  pvc:
    storageClassName: px-csi-db
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
