apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-image
  namespace: pxbbq
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/minimal/releases/noble/release/ubuntu-24.04-minimal-cloudimg-amd64.img"
  pvc:
    storageClassName: px-csi-db
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
