apiVersion: v1
kind: Service
metadata:
  name: testvm1-ssh
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/vm: testvm1
  type: NodePort
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: testvm1
  name: testvm1
spec:
  dataVolumeTemplates:
    - metadata:
        name: ubuntu-dv
      spec:
        pvc:
          storageClassName: px-virtualization
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
        source:
          http:
            url: "https://cloud-images.ubuntu.com/minimal/releases/mantic/release/ubuntu-23.10-minimal-cloudimg-amd64.img"
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: testvm1
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: test-datavolume
            - bootOrder: 2
              disk:
                bus: virtio
              name: cloudinitvolume
          interfaces:
          - name: default
            masquerade: {}    
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}      
      volumes:
        - dataVolume:
            name: ubuntu-dv
          name: test-datavolume
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: testvm1
              users:
                - name: kubevirt
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  passwd: $6$Q1dGl.LfuMeS8RPP$b4xynn.Z3n2/h.YqOV90H7GzoAfjLKPMAKP1rzCeeBxiYNhROkxOXAC4rmQNbQf3oZ.Om8/Q7W8XmTgHsdoLw.
                  shell: /bin/bash
                  home: /home/kubevirt
                  lock_passwd: false
              runcmd:
                - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
                - systemctl restart ssh  
          name: cloudinitvolume
